### ISSUE TITLE
请问做过耗时对比实验吗？

### ISSUE THREAD

**Issue by drzqb** [DaDaMrX/ReaLiSe#1]
看论文，模型的参数量基本超过bert的1.5倍了，请问做过耗时对比实验吗？如果采用同等规模参数量的bert，bert的sighan测试指标实验结果会怎么样呢？

**Comment by DaDaMrX** [comment]
没有专门做过耗时对比实验，我们实验的时候用2块P40 GPU，每个epoch 1.5小时，我们觉得这个时间长度还在可接受范围内。

实验中我们用的是BERT-base，要是换成BERT-large，参数量就是BERT-base的三倍，所以实际上找不到同等参数量的BERT来实验。我们也用BERT-large实验过，效果没有我们的模型好。
