### ISSUE TITLE
SIGHAN2013 2014 实验结果

### ISSUE THREAD

**Issue by LuckyyySTA** [DaDaMrX/ReaLiSe#10]
您好，感谢开源！
用 BERT-finetune baseline 跑 SIGHAN2013、2014 实验的时候，仅仅更改 dev predict 数据集，但是结果差特别多，SIGHAN2015 的实验结果能跑出来，请问是我的操作设置错了吗，怎么结果差这么多？期待回复~

**Comment by Toddzhangwj** [comment]
我也遇到了相同的问题，SIGHAN14上的实验结果无法复现

**Comment by Toddzhangwj** [comment]
> 您好，感谢开源！ 用 BERT-finetune baseline 跑 SIGHAN2013、2014 实验的时候，仅仅更改 dev predict 数据集，但是结果差特别多，SIGHAN2015 的实验结果能跑出来，请问是我的操作设置错了吗，怎么结果差这么多？期待回复~

您好，请问您这个问题有解决嘛，还有就是您在SIGHAN14数据集上复现的效果如何呀，谢谢。

**Comment by LuckyyySTA** [comment]
> > 您好，感谢开源！ 用 BERT-finetune baseline 跑 SIGHAN2013、2014 实验的时候，仅仅更改 dev predict 数据集，但是结果差特别多，SIGHAN2015 的实验结果能跑出来，请问是我的操作设置错了吗，怎么结果差这么多？期待回复~
> 
> 您好，请问您这个问题有解决嘛，还有就是您在SIGHAN14数据集上复现的效果如何呀，谢谢。

换了很多次随机种子，用 BERT 模型 SIGHAN14的纠错f1大概在64.3，SIGHAN15大概在72，但是SIGHAN2013在56左右，SIGHAN14之前的随机种子跑出来差了5-6个点，这个是我跑的最好的SIGHAN14的结果，和论文的BERT报的差不多，但是SIGHAN13怎么跑都差特别多，也没有发现问题在哪。

**Comment by Toddzhangwj** [comment]
SIGHAN13上对输出的数据进行了处理，您可以看看。我目前发现的规律是，dev集不能改，只能改test集，您试试dev用sighan15，test用sighan14跑一次，可能会稍微有提升在sighan14上。







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月18日(星期一) 下午5:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DaDaMrX/ReaLiSe] SIGHAN2013 2014 实验结果 (Issue #10)





   
您好，感谢开源！ 用 BERT-finetune baseline 跑 SIGHAN2013、2014 实验的时候，仅仅更改 dev predict 数据集，但是结果差特别多，SIGHAN2015 的实验结果能跑出来，请问是我的操作设置错了吗，怎么结果差这么多？期待回复~
  
您好，请问您这个问题有解决嘛，还有就是您在SIGHAN14数据集上复现的效果如何呀，谢谢。
  
换了很多次随机种子，用 BERT 模型 SIGHAN14的纠错f1大概在64.3，SIGHAN15大概在72，但是SIGHAN2013在56左右，SIGHAN14之前的随机种子跑出来差了5-6个点，这个是我跑的最好的SIGHAN14的结果，和论文的BERT报的差不多，但是SIGHAN13怎么跑都差特别多，也没有发现问题在哪。

**Comment by wangwang110** [comment]
感谢开源，代码基本不用作什么修改就能跑起来。相同的数据，相同的参数，这是我的测试的结果
15
sent-correct-acc: 82.73
sent-correct-f1: 75.94
sent-correct-p: 73.82
sent-correct-r: 78.19
sent-detect-acc: 83.55
sent-detect-f1: 77.56
sent-detect-p: 75.39
sent-detect-r: 79.85

14
sent-correct-acc: 76.55
sent-correct-f1: 65.22
sent-correct-p: 64.13
sent-correct-r: 66.35
sent-detect-acc: 77.59
sent-detect-f1: 67.30
sent-detect-p: 66.17
sent-detect-r: 68.46

13
sent-correct-acc: 80.80
sent-correct-f1: 83.30
sent-correct-p: 86.14
sent-correct-r: 80.64
sent-detect-acc: 82.20
sent-detect-f1: 84.79
sent-detect-p: 87.68
sent-detect-r: 82.08

**Comment by Candice52** [comment]
我想问一下，大家都是用了作者在merge后预训练好的模型继续训练的么？我想试着自己训练一个拼英pho编码器，应该用哪个数据集呢？data_processing.py可以得到这个数据集么？

**Comment by Neutralzz** [comment]
@wangwang110 @LuckyyySTA @Toddzhangwj @Candice52 

Please refer to [this issue](https://github.com/DaDaMrX/ReaLiSe/issues/12).
