### ISSUE TITLE
数据文件没有找到，以及模型链接失效无法打开

### ISSUE THREAD

**Issue by YINGPENGZH** [DaDaMrX/ReaLiSe#2]
如题

**Comment by DaDaMrX** [comment]
感谢对我们工作的关注，文件还在整理中，数据文件和模型我们会尽快上传

**Comment by YINGPENGZH** [comment]
> 感谢对我们工作的关注，文件还在整理中，数据文件和模型我们会尽快上传
你好，搭好环境后运行train.sh遇到这个错误，请问这是什么情况？
File "src/run.py", line 453, in <module>
    global_step, tr_loss = train(args, model, tokenizer, batch_processor)
  File "src/run.py", line 133, in train
    total_dataset = create_dataset(args, args.train_file)
  File "src/run.py", line 67, in create_dataset
    dataset = pickle.load(open(input_file, 'rb'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 66: invalid continuation byte

**Comment by DaDaMrX** [comment]
@YINGPENGZH 已经更新了data的下载链接，这次应该没问题了。
