### ISSUE TITLE
issues on src/run.py

### ISSUE THREAD

**Issue by Yangyi-Chen** [DaDaMrX/ReaLiSe#8]
Hi!  I found the code in src/run.py 432 has some problems "model = model_class.from_pretrained(args.model_name_or_path, config=config, cache_dir=args.cache_dir if args.cache_dir else None)".  The error message is :ValueError: Parameter config in `SpellBertPho2ResArch3(config)` should be an instance of class `PretrainedConfig`. To create a model from a pretrained model use `model = SpellBertPho2ResArch3.from_pretrained(PRETRAINED_MODEL_NAME)`.

**Comment by DaDaMrX** [comment]
How about run the command advance `pip install --editable .`，or add the command to `train.sh` and `test.sh`.
