### ISSUE TITLE
关于评测方法

### ISSUE THREAD

**Issue by li-aolong** [DaDaMrX/ReaLiSe#9]
你好，文章中貌似没有提到使用什么方法评测的，是官方工具吗？

**Comment by DaDaMrX** [comment]
你好，评测方法是与FASpell和SpellGCN一致，但是是自己实现的。

ReaLiSe评测脚本：[src/metric_core.py](https://github.com/DaDaMrX/ReaLiSe/blob/master/src/metric_core.py)。

FASpell评测代码：[faspell.py Line508](https://github.com/iqiyi/FASPell/blob/master/faspell.py#L508)

与sighan官方的评测方法有一些变化。
